---
abstract: 'An implementation of Apache::Session module for NoSQL databases'
author:
  - 'Thomas Chemineau <thomas.chemineau@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Apache-Session-NoSQL
no_index:
  directory:
    - t
    - inc
recommends:
  Net::Cassandra: '0'
  Redis: '0'
requires:
  Apache::Session: '0'
version: v0.2.1
x_deprecated: 1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
