--- #YAML:1.0
name:               Apache-Session-NoSQL
version:            0.1
abstract:           An implementation of Apache::Session module for NoSQL databases
author:
    - Thomas Chemineau <thomas.chemineau@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache::Session:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Net::Cassandra:  0
    Redis:           0
